- platform: mqtt
  name: 'FTDI energy consumption total'
  state_topic: 'homeassistant/sensor/ftdi/energy_consumption_total'
  unit_of_measurement: 'kWh'
  unique_id: 'ftdi_energy_consumption_total'
  device_class: energy
  state_class: measurement
  value_template: '{{ value | float(0) | round(1) }}'

- platform: mqtt
  name: 'FTDI energy production total'
  state_topic: 'homeassistant/sensor/ftdi/energy_production_total'
  unit_of_measurement: 'kWh'
  unique_id: 'ftdi_energy_production_total'
  device_class: energy
  state_class: measurement
  value_template: '{{ value | float(0) | round(1) }}'

- platform: mqtt
  name: 'FTDI power consumption'
  state_topic: 'homeassistant/sensor/ftdi/power_consumption'
  unit_of_measurement: 'kW'
  unique_id: 'ftdi_power_consumption'
  device_class: power
  state_class: measurement
  value_template: '{{ value | float(0) | round(1) }}'

- platform: mqtt
  name: 'FTDI power production'
  state_topic: 'homeassistant/sensor/ftdi/power_production'
  unit_of_measurement: 'kW'
  unique_id: 'ftdi_power_production'
  device_class: power
  state_class: measurement
  value_template: '{{ value | float(0) | round(1) }}'

- platform: mqtt
  name: 'FTDI consumption phase l1'
  state_topic: 'homeassistant/sensor/ftdi/consumption_phase_l1'
  unit_of_measurement: 'kW'
  unique_id: 'ftdi_consumption_phase_l1'
  device_class: power
  state_class: measurement
  value_template: '{{ value | float(0) | round(1) }}'

- platform: mqtt
  name: 'FTDI consumption phase l2'
  state_topic: 'homeassistant/sensor/ftdi/consumption_phase_l2'
  unit_of_measurement: 'kW'
  unique_id: 'ftdi_consumption_phase_l2'
  device_class: power
  state_class: measurement
  value_template: '{{ value | float(0) | round(1) }}'

- platform: mqtt
  name: 'FTDI consumption phase l3'
  state_topic: 'homeassistant/sensor/ftdi/consumption_phase_l3'
  unit_of_measurement: 'kW'
  unique_id: 'ftdi_consumption_phase_l3'
  device_class: power
  state_class: measurement
  value_template: '{{ value | float(0) | round(1) }}'

- platform: mqtt
  name: 'FTDI production phase l1'
  state_topic: 'homeassistant/sensor/ftdi/production_phase_l1'
  unit_of_measurement: 'kW'
  unique_id: 'ftdi_production_phase_l1'
  device_class: power
  state_class: measurement
  value_template: '{{ value | float(0) | round(1) }}'

- platform: mqtt
  name: 'FTDI production phase l2'
  state_topic: 'homeassistant/sensor/ftdi/production_phase_l2'
  unit_of_measurement: 'kW'
  unique_id: 'ftdi_production_phase_l2'
  device_class: power
  state_class: measurement
  value_template: '{{ value | float(0) | round(1) }}'

- platform: mqtt
  name: 'FTDI production phase l3'
  state_topic: 'homeassistant/sensor/ftdi/production_phase_l3'
  unit_of_measurement: 'kW'
  unique_id: 'ftdi_production_phase_l3'
  device_class: power
  state_class: measurement
  value_template: '{{ value | float(0) | round(1) }}'

- platform: mqtt
  name: 'FTDI voltage phase l1'
  state_topic: 'homeassistant/sensor/ftdi/voltage_phase_l1'
  unit_of_measurement: 'V'
  unique_id: 'ftdi_voltage_phase_l1'
  device_class: voltage
  state_class: measurement
  value_template: '{{ value | float(0) | round(1) }}'

- platform: mqtt
  name: 'FTDI voltage phase l2'
  state_topic: 'homeassistant/sensor/ftdi/voltage_phase_l2'
  unit_of_measurement: 'V'
  unique_id: 'ftdi_voltage_phase_l2'
  device_class: voltage
  state_class: measurement
  value_template: '{{ value | float(0) | round(1) }}'

- platform: mqtt
  name: 'FTDI voltage phase l3'
  state_topic: 'homeassistant/sensor/ftdi/voltage_phase_l3'
  unit_of_measurement: 'V'
  unique_id: 'ftdi_voltage_phase_l3'
  device_class: voltage
  state_class: measurement
  value_template: '{{ value | float(0) | round(1) }}'

- platform: mqtt
  name: 'FTDI current phase l1'
  state_topic: 'homeassistant/sensor/ftdi/current_phase_l1'
  unit_of_measurement: 'A'
  unique_id: 'ftdi_current_phase_l1'
  device_class: current
  state_class: measurement
  value_template: '{{ value | float(0) | round(1) }}'

- platform: mqtt
  name: 'FTDI current phase l2'
  state_topic: 'homeassistant/sensor/ftdi/current_phase_l2'
  unit_of_measurement: 'A'
  unique_id: 'ftdi_current_phase_l2'
  device_class: current
  state_class: measurement
  value_template: '{{ value | float(0) | round(1) }}'

- platform: mqtt
  name: 'FTDI current phase l3'
  state_topic: 'homeassistant/sensor/ftdi/current_phase_l3'
  unit_of_measurement: 'A'
  unique_id: 'ftdi_current_phase_l3'
  device_class: current
  state_class: measurement
  value_template: '{{ value | float(0) | round(1) }}'
